import type { Metadata } from "next";
import "./globals.css";
import { Archivo } from "next/font/google";

const font = Archivo({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} dark antialiased`}>{children}</body>
    </html>
  );
}
